const {
  MONGO_URI,
  DB_USER,
  DB_PASS,
  DB_HOST,
  DB_PORT,
  DB_NAME,
  SECRET_KEY,
  ACCESTOKENSECRET,
  REFRESHTOKENSECRET,
  PORT,
  NODE_ENV,
  FRONTEND_URL,
  ENGINE_API_KEY,
  ENGINE_SCHEMA_TAG,
  DEBUGPRINTREPORTS,
} = process.env;

module.exports = {
  APOLLO: {
    ENGINE_API_KEY,
    ENGINE_SCHEMA_TAG,
    DEBUGPRINTREPORTS,
  },

  FRONTEND_URL,
  PORT: PORT || '4000',
  NODE_ENV: NODE_ENV || 'development',

  SECRET_KEY: SECRET_KEY || 'ldeVaDcqH33N6',
  ACCESTOKENSECRET: ACCESTOKENSECRET || 'secret1',
  REFRESHTOKENSECRET: REFRESHTOKENSECRET || 'secret2',

  mongoUri: MONGO_URI || `mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}`,
};
